name = "acaring-contact-api"
main = "src/index.js"
compatibility_date = "2026-06-08"
workers_dev = true

[[routes]]
pattern = "acaringadulthome.com/api/contact*"
zone_name = "acaringadulthome.com"

[[routes]]
pattern = "www.acaringadulthome.com/api/contact*"
zone_name = "acaringadulthome.com"

[[send_email]]
name = "EMAIL"
destination_address = "acaringadulthome@gmail.com"
